/** Table-only Excel export. Options are not stored on the query. */
import { useState } from "react";
import { createPortal } from "react-dom";
import {
  DEFAULT_EXCEL_OPTIONS,
  ExcelExportOptions,
  rowsToXlsxBuffer,
  xlsxFileName,
} from "../../lib/excelExport";
import { APP_NAME } from "../../lib/brand";
import { Icon, faDownload, faXmark } from "../Icon";
import { useTheme } from "../settings/ThemeProvider";

export default function ExcelExportDialog({
  rows,
  osName,
  title,
  totalCount,
  onClose,
}: {
  rows: Record<string, unknown>[];
  osName?: string;
  title?: string;
  totalCount?: number;
  onClose: () => void;
}) {
  const { pack } = useTheme();
  const [opts, setOpts] = useState<ExcelExportOptions>(DEFAULT_EXCEL_OPTIONS);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  function patch(p: Partial<ExcelExportOptions>) {
    setOpts((o) => ({ ...o, ...p }));
  }

  async function exportXlsx() {
    setError(null);
    setBusy(true);
    try {
      const buf = await rowsToXlsxBuffer(rows, opts, {
        osName,
        title,
        totalCount,
        themeKind: pack.kind,
        themeAccent: pack.tokens.accent,
        themeAccent2: pack.tokens.accent2,
        themeOnAccent: pack.tokens.onAccent,
        themeText: pack.tokens.text,
        themeMuted: pack.tokens.muted,
        themeSurface: pack.tokens.surfaceSolid,
        themeBorder: pack.tokens.border,
      });
      const blob = new Blob([buf], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = xlsxFileName(osName);
      a.click();
      URL.revokeObjectURL(url);
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  }

  const outline = opts.layout === "outline";

  return createPortal(
    <div
      className="import-overlay"
      onMouseDown={(e) => {
        if (e.target === e.currentTarget && !busy) onClose();
      }}
    >
      <div className={`import-dialog excel-export-dialog${error ? " shake" : ""}`}>
        <div className="spread">
          <label className="lbl" style={{ marginBottom: 0 }}>
            {APP_NAME} Result Set
          </label>
          <button type="button" className="icon-btn" onClick={onClose} disabled={busy} aria-label="Close">
            <Icon icon={faXmark} />
          </button>
        </div>
        <p className="muted" style={{ margin: "8px 0 0" }}>
          Nested payload, including child collections. Not saved on the query.
          Uses the {pack.name} theme. Print is always landscape with repeating titles
          and a Generated by {APP_NAME} footer. Excel cannot nest a child table
          inside a parent cell the way the results tree does -- each relationship
          is its own sheet, with click-through between them.
        </p>

        <fieldset className="excel-opt" disabled={busy}>
          <legend>Layout</legend>
          <label>
            <input
              type="radio"
              name="xlsx-layout"
              checked={opts.layout === "sheets"}
              onChange={() => patch({ layout: "sheets" })}
            />
            One sheet per relationship. Click a child name to open that parent's
            rows; click Parent to go back
          </label>
          <label>
            <input
              type="radio"
              name="xlsx-layout"
              checked={opts.layout === "outline"}
              onChange={() => patch({ layout: "outline" })}
            />
            Same sheet: parent once, blank ancestor cells (Excel outline +/-)
          </label>
          <label>
            <input
              type="radio"
              name="xlsx-layout"
              checked={opts.layout === "leaves"}
              onChange={() => patch({ layout: "leaves" })}
            />
            Flat leaves: parent columns repeated on every child (PivotTable)
          </label>
          {opts.layout === "sheets" && (
            <pre className="excel-preview" aria-hidden>
{`MXAPIWO
wonum  status  woactivity  asset
1000   APPR    2 rows      Open     <- click woactivity

woactivity
Parent  wonum    status
1000    1000.1   WAPPR              <- click Parent to return
1000    1000.2   APPR`}
            </pre>
          )}
          {outline && (
            <pre className="excel-preview" aria-hidden>
{`wonum  status  woactivity.wonum
1000   APPR
               1000.1
               1000.2`}
            </pre>
          )}
        </fieldset>

        <fieldset className="excel-opt" disabled={busy}>
          <legend>Include</legend>
          <label className="excel-check">
            <input
              type="checkbox"
              checked={opts.includeNested}
              onChange={(e) => patch({ includeNested: e.target.checked })}
            />
            Grandchild and deeper collections
          </label>
          {opts.layout === "leaves" && (
            <label className="excel-check">
              <input
                type="checkbox"
                checked={opts.includeParentsWithoutChildren}
                onChange={(e) => patch({ includeParentsWithoutChildren: e.target.checked })}
              />
              Also write a parent-only row when children exist
            </label>
          )}
        </fieldset>

        <fieldset className="excel-opt" disabled={busy}>
          <legend>Workbook</legend>
          <label className="excel-check">
            <input
              type="checkbox"
              checked={opts.coverSheet}
              onChange={(e) => patch({ coverSheet: e.target.checked })}
            />
            Cover sheet titled {APP_NAME} Result Set
          </label>
          <label className="excel-check">
            <input
              type="checkbox"
              checked={opts.groupHeaders}
              onChange={(e) => patch({ groupHeaders: e.target.checked })}
              disabled={!outline}
            />
            Two-row headers (relationship group, then field)
          </label>
          <label className="excel-check">
            <input
              type="checkbox"
              checked={opts.outlineGroups}
              onChange={(e) => patch({ outlineGroups: e.target.checked })}
              disabled={!outline}
            />
            Excel row grouping (+/- to collapse children)
          </label>
          <label className="excel-check">
            <input
              type="checkbox"
              checked={opts.layout === "leaves" && opts.excelTable}
              onChange={(e) => patch({ excelTable: e.target.checked })}
              disabled={outline || opts.layout === "sheets"}
            />
            Excel Table (filter/sort). Off for click-through sheets and outline:
            tables drop hyperlinks, and they conflict with row grouping.
          </label>
          <label className="excel-check">
            <input
              type="checkbox"
              checked={opts.freeze}
              onChange={(e) => patch({ freeze: e.target.checked })}
            />
            Freeze header rows
          </label>
          <label className="excel-check">
            <input
              type="checkbox"
              checked={opts.autoFilter}
              onChange={(e) => patch({ autoFilter: e.target.checked })}
            />
            AutoFilter on field headers
          </label>
        </fieldset>

        {error && <p className="warn-chip">{error}</p>}
        <div className="row" style={{ justifyContent: "flex-end", marginTop: 16 }}>
          <button type="button" className="ghost" onClick={onClose} disabled={busy}>
            Cancel
          </button>
          <button type="button" className="go" onClick={() => void exportXlsx()} disabled={busy || rows.length === 0}>
            <Icon icon={faDownload} /> {busy ? "Building..." : "Download .xlsx"}
          </button>
        </div>
      </div>
    </div>,
    document.body,
  );
}
