/**
 * Canonical Builder-tour sample. Catalog copy reads EXAMPLE; demo-story
 * hydrates TOUR_QUERY through the same import path as paste-import.
 */
export const EXAMPLE = {
  os: "MXAPIWO",
  fields: "wonum, worktype, status, description, assetnum, ...",
  child: "ASSET",
  childPath: "ASSET -> ASSET_PARENT -> OPENWO",
  childFields: "assetnum, description, status, location",
  child2: "WO_LOCATION",
  child3: "WOACTIVITY",
  child3Path: "WOACTIVITY -> ACTIVEASSETMETER -> ASSET",
  hop: "ASSET_PARENT",
  hopLeaf: "OPENWO",
  where: "istask=0, historyflag=0, assetnum=*, worktype=PM",
  timeline: "-3 months on changedate",
  domain: "status=WAPPR",
  sort: "wonum ascending",
  pageSize: 10,
};

export const TOUR_PARENT_FIELDS = [
  "wonum",
  "workorderid",
  "worktype",
  "pluspapplypstochild",
  "assetnum",
  "changedate",
  "cinum",
  "description",
  "failurecode",
  "historyflag",
  "istask",
  "location",
  "orgid",
  "pluspcustomer",
  "problemcode",
  "reportdate",
  "reportedby",
  "siteid",
  "status",
  "woclass",
  "crewworkgroup",
  "displaywonum",
  "filterbyworkzone",
  "hasfollowupwork",
  "assetlocpriority",
  "wopriority",
];

export const TOUR_WHERE = [
  { field: "istask", op: "=", value: "0" },
  { field: "historyflag", op: "=", value: "0" },
  { field: "assetnum", op: "=", value: "*" },
  { field: "worktype", op: "=", value: "PM" },
] as const;

/** Live os_query_builder args for the tour sample (PM work orders). */
export const TOUR_QUERY: Record<string, unknown> = {
  opAction: "query",
  osName: "MXAPIWO",
  select: {
    fields: [
      ...TOUR_PARENT_FIELDS,
      "rel.ASSET{autowogen,assetnum,changedate,cinum,description,failurecode,location,orgid,pluspcustomer,priority,siteid,status,rel.ASSET_PARENT{assetid,assetnum,changedate,description,failurecode,location,orgid,pluspcustomer,priority,siteid,status,rel.OPENWO{assetnum,changedate,cinum,description,failurecode,historyflag,istask,location,orgid,pluspcustomer,problemcode,reportdate,reportedby,siteid,status,woclass,wonum,workorderid,worktype}}}",
      "rel.WO_LOCATION{description,location,orgid,status}",
      "rel.WOACTIVITY{woclass,workorderid,worktype,pluspapplypstochild,assetnum,changedate,cinum,description,failurecode,historyflag,istask,location,orgid,pluspcustomer,problemcode,reportdate,reportedby,siteid,status,wonum,crewworkgroup,displaywonum,filterbyworkzone,hasfollowupwork,rel.ACTIVEASSETMETER{assetid,assetnum,changedate,orgid,siteid,rel.ASSET{assetid,assetnum,changedate,cinum,description,failurecode,location,orgid,pluspcustomer,priority,siteid,status,wonum}}}",
    ],
  },
  pageSize: 10,
  collectioncount: true,
  searchAttributes: [
    "wonum",
    "workorderid",
    "worktype",
    "assetnum",
    "changedate",
    "cinum",
    "description",
    "failurecode",
    "location",
    "orgid",
    "pluspcustomer",
    "problemcode",
    "reportdate",
    "reportedby",
    "siteid",
    "status",
    "woclass",
    "crewworkgroup",
    "displaywonum",
    "assetlocpriority",
    "wopriority",
    "asset.assetnum",
    "asset.changedate",
    "asset.cinum",
    "asset.description",
    "asset.failurecode",
    "asset.location",
    "asset.orgid",
    "asset.pluspcustomer",
    "asset.priority",
    "asset.siteid",
    "asset.status",
    "wo_location.description",
    "wo_location.location",
    "wo_location.orgid",
    "wo_location.status",
    "woactivity.woclass",
    "woactivity.workorderid",
    "woactivity.worktype",
    "woactivity.assetnum",
    "woactivity.changedate",
    "woactivity.cinum",
    "woactivity.description",
    "woactivity.failurecode",
    "woactivity.location",
    "woactivity.orgid",
    "woactivity.pluspcustomer",
    "woactivity.problemcode",
    "woactivity.reportdate",
    "woactivity.reportedby",
    "woactivity.siteid",
    "woactivity.status",
    "woactivity.wonum",
    "woactivity.crewworkgroup",
    "woactivity.displaywonum",
    "woactivity.activeassetmeter.asset.assetnum",
    "woactivity.activeassetmeter.asset.changedate",
    "woactivity.activeassetmeter.asset.cinum",
    "woactivity.activeassetmeter.asset.description",
    "woactivity.activeassetmeter.asset.failurecode",
    "woactivity.activeassetmeter.asset.location",
    "woactivity.activeassetmeter.asset.orgid",
    "woactivity.activeassetmeter.asset.pluspcustomer",
    "woactivity.activeassetmeter.asset.priority",
    "woactivity.activeassetmeter.asset.siteid",
    "woactivity.activeassetmeter.asset.status",
    "asset.asset_parent.assetid",
    "asset.asset_parent.assetnum",
    "asset.asset_parent.changedate",
    "asset.asset_parent.description",
    "asset.asset_parent.failurecode",
    "asset.asset_parent.location",
    "asset.asset_parent.orgid",
    "asset.asset_parent.pluspcustomer",
    "asset.asset_parent.priority",
    "asset.asset_parent.siteid",
    "asset.asset_parent.status",
    "asset.asset_parent.openwo.assetnum",
    "asset.asset_parent.openwo.changedate",
    "asset.asset_parent.openwo.cinum",
    "asset.asset_parent.openwo.description",
    "asset.asset_parent.openwo.failurecode",
    "asset.asset_parent.openwo.location",
    "asset.asset_parent.openwo.orgid",
    "asset.asset_parent.openwo.pluspcustomer",
    "asset.asset_parent.openwo.problemcode",
    "asset.asset_parent.openwo.reportdate",
    "asset.asset_parent.openwo.reportedby",
    "asset.asset_parent.openwo.siteid",
    "asset.asset_parent.openwo.status",
    "asset.asset_parent.openwo.woclass",
    "asset.asset_parent.openwo.wonum",
    "asset.asset_parent.openwo.workorderid",
    "asset.asset_parent.openwo.worktype",
    "woactivity.activeassetmeter.assetid",
    "woactivity.activeassetmeter.assetnum",
    "woactivity.activeassetmeter.changedate",
    "woactivity.activeassetmeter.orgid",
    "woactivity.activeassetmeter.siteid",
    "woactivity.activeassetmeter.asset.assetid",
    "woactivity.activeassetmeter.asset.wonum",
  ],
  where: {
    conditions: TOUR_WHERE.map((c) => ({ ...c })),
  },
  tlrange: "-3M",
  tlattribute: "changedate",
  domaininternalwhere: "status=WAPPR",
  orderBy: {
    rules: ["+wonum"],
  },
  childOptions: [
    {
      relationship: "OPENWO",
      where: {
        conditions: [{ field: "istask", op: "=", value: "0" }],
      },
      path: ["ASSET", "ASSET_PARENT", "OPENWO"],
      limit: 50,
    },
  ],
};
